index_directory: "./rag_index"
chunk_size: 1024
embedding_model: "thenlper/gte-large"
ollama_model: "mixtral"
chroma_collection: "sagemaker_docs"
documents_dir: "sagemaker_documentation"
query_history: "queries_database.jsonl"
