index_directory: ".rag_index"
chunk_size: 512
embedding_model: "thenlper/gte-large"
ollama_model: "mixtral"
chroma_collection: "documents_chroma_db"
documents_dir: "documents"
query_history: "queries_database.jsonl"
